### ISSUE TITLE
Stuck on panic.apple to report the error

### ISSUE THREAD

**Issue by 0x86e3x4** [ho1yspirt/ideapad-s340-14api-hackintosh#1]
Heyy, spirt i trying to install macos sanoma to my asus vivobook 15 x512DA 

8gb ram ,ryzen 3500u , for wifi and bluetooth qualcom Atheros QCA9377 ,for nvme ssd kingston OM8PXP3512F-AB 512gb
can you give me some pointers

**Comment by ho1yspirt** [comment]
Sup @0x86e3x4.
1.1. Did you check these repos?
- https://github.com/navaneeth191997/Hackintosh-for-X512DA-Ryzen5-3500
- https://github.com/LukeDevsE/Asus-Vivobook-X512DA

1.2. If so, try to reach owners of these repos by opening issues in respect repository.
2.1. If not, try them first, these repos seems to fit your machine more, than this repo, therefore its for lenovos in the first place.
2.2. If you still want to try it, you need to remove everything related to intel wifi\bluetooth module (your is qualcomm), generate SSDTs specifically for your hardware and something else that i forgot.

If it solved your issue, please close it, thank you.

<details>
  <summary>Off-Topic</summary>

  I can't help more, since I fell out of the hackintosh related theme around a year ago by getting mac.
  
</details>

**Comment by 0x86e3x4** [comment]
i managed to fix it. now i can dualboot successfully. but everything works except for wifi
